# -*- coding: utf-8 -*-
"""Day2_AI_Eng_Gradio_Lab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yjSNzg1Bec_dncSAelX1LN64wbgYvAUU

### Question

Build a gradio UI where a user can supply a textual input and the output is the sentiment of that input.

### Instructions


1. figure out how to generate sentiment using a hf model - dont worry about gradio yet. you are free to use any hf model of your choice.
3. once summarization is figured, build the gradio UI using Interface!
"""

!pip install transformers datasets evaluate accelerate

from transformers import pipeline

# For a public model (e.g., sentiment analysis)
classifier = pipeline("sentiment-analysis")
result = classifier("Hugging Face models in Colab are great!")
print(result)

!pip install gradio

import gradio as gr



# Create the interface
# inputs='text' specifies a textbox input
# outputs='text' specifies a textbox output
demo = gr.Interface(fn=classifier, inputs="text", outputs="text")

# Launch the interface
# The launch() method starts a local server
# You can access the interface at the displayed URL
demo.launch()

